---
#This role will install mysql service
- name: Install mysql repo
  yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present 

- name: Install mysql package
  yum: name=mysql-server state=present

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.temp dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ password }} priv=*.*:ALL host='%' state=present
