version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    network_mode: "host"
    restart: always
    #ports:
    #- 9090:9090
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention=180d
    volumes:
      - /data/prometheus:/prometheus:rw
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerting_rule:/etc/prometheus/alerting_rule:ro
      - ./recording_rule:/etc/prometheus/recording_rule:ro
    #env_file:
      #- ./prometheus-compose.yml
