#! /bin/sh
#
# Start/Stop murder-tracker
#
# chkconfig: 345 80 10
# description: murder-tracker
# processname: murder-tracker

if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi




name="murder-tracker"
murder_tracker_bin="/opt/app/murder/dist/murder_tracker.py"
murder_tracker_log="/opt/logs/murder/murder_tracker.log"
murder_tracker_data="/opt/data/murder/tracker_data"
murder_user=murder


find_tracker_process () {
    PID=`ps -ef | grep murder_tracker | grep python |grep -v $0|grep -v grep|grep -v sh|grep -v root| awk '{ print $2 }'`
}

start () {
    getent passwd $murder_user  >/dev/null || useradd -r -s /sbin/nologin $murder_user
    LOG_DIR=`dirname ${murder_tracker_log}`
    DATA_DIR=`dirname ${murder_tracker_data}`
    if [ ! -d $LOG_DIR ]; then
      echo -e  "\e[35mLog dir ${LOG_DIR} doesn't exist. Creating\e[0m"
      mkdir -p $LOG_DIR     
    fi
    if [ ! -d $DATA_DIR ]; then
      echo -e  "\e[35mLog dir ${DATA_DIR} doesn't exist. Creating\e[0m"
      mkdir -p $DATA_DIR
    fi
    chown -R $murder_user:$murder_user $DATA_DIR  $LOG_DIR

    find_tracker_process
    if [ "$PID" != "" ]; then
       echo -e  "\e[35m$name is already running!\e[0m"
    else
       daemon --user $murder_user nohup python $murder_tracker_bin > /dev/null 2>&1 &
#        nohup  python $murder_tracker_bin  > /dev/null 2>&1 &
       echo -e "\e[35mStarting $name Done\e[0m"
    fi
}



stop () {
    find_tracker_process
    if [ "$PID" != "" ]; then
        echo -e "\e[35mStopping $name\e[0m"
        kill $PID
    else
        echo -e "\e[35m$name is not running yet\e[0m"
    fi
}

case $1 in
start)
        start
        ;;
stop)
        stop
        exit 0
        ;;
reload)
        stop
        sleep 2
        start
        ;;
restart)
        stop
        sleep 2
        start
        ;;
status)
        find_tracker_process
        if [ "$PID" != "" ]; then
          echo -e "\e[35m$name is running: $PID\e[0m"
          exit 0
        else
          echo -e "\e[35m$name is not running\e[0m"
          exit 1
        fi
        ;;
*)
        echo -e "\e[35mUsage: $0 {start|stop|restart|reload|status|configtest}\e[0m"
        RETVAL=1
esac
exit 0
