---
- hosts: bigops
  remote_user: root
  gather_facts: yes
  tasks:  
  - name: save iptables rule
    shell: |
      iptables-save > /tmp/iptables.bak$(date +"%F-%T")
  - name: Stop Firewall in linux7
    systemd: name={{item}} state=stopped enabled=no
    with_items: [firewalld]
    when: ansible_distribution == "CentOS" and ( ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8" )
  - name: Stop Firewall in linux6
    service: name={{item}} state=stopped enabled=no
    with_items: [iptables,ip6tables]
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
    #ignore_errors: true
