groups:
- name: code_center
  rules:
  - alert: 查询券码
    expr: delta(code_center_query_code_count{result="fail_sys"}[5m]) > 10
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "应用服务|code-center|，主机|{{$labels.host}}|，5分钟内查询券码详情累计失败次数大于10，请核查失败原因"

  - alert: 验证券码
    expr: delta(code_center_verify_code_count{result="fail_sys"}[5m]) > 10
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "应用服务|code-center|，主机|{{$labels.host}}|，5分钟内验证券码累计失败次数大于10，请核查失败原因"
