groups:
- name: node_status 
  rules:
  - alert: AgentStatusDown
    expr: up{job="wwj_v8"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: 主机|{{$labels.hostname}}|未能被监控，请检查与Prometheus系统的通信状态
