version: "2"
services:
  redis-m:
    container_name: redis-m
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/redis.conf"]
    entrypoint: ["redis-server"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.10
    volumes:
      - ./config/r_master.conf:/etc/redis.conf
    ports:
      - "6379:6379"
  redis-s:
    container_name: redis-s
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/redis.conf"]
    entrypoint: ["redis-server"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.11
    volumes:
      - ./config/r_slave.conf:/etc/redis.conf
    links:
      - redis-m
networks:
  redis_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24
