version: "2"
services:
  redis-m:
    container_name: redis-m
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/redis.conf"]
    entrypoint: ["redis-server"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.10
    volumes:
      - ./config/r_master.conf:/etc/redis.conf
    ports:
      - "6379:6379"
  redis-s:
    container_name: redis-s
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/redis.conf"]
    entrypoint: ["redis-server"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.11
    volumes:
      - ./config/r_slave.conf:/etc/redis.conf
    links:
      - redis-m
  redis-ss:
    container_name: redis-ss
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/redis.conf"]
    entrypoint: ["redis-server"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.9
    volumes:
      - ./config/r_sslave.conf:/etc/redis.conf
    links:
      - redis-m
  sentinel-a:
    container_name: sentinel-a
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/sentinel.conf"]
    entrypoint: ["redis-sentinel"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.12
    volumes:
      - ./config/sentinel-a.conf:/etc/sentinel.conf
    links:
      - redis-m
      - redis-s
      - redis-ss
  sentinel-b:
    container_name: sentinel-b
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/sentinel.conf"]
    entrypoint: ["redis-sentinel"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.13
    volumes:
      - ./config/sentinel-b.conf:/etc/sentinel.conf
    links:
      - redis-m
      - redis-s
      - redis-ss
  sentinel-c:
    container_name: sentinel-c
    image: redis:5.0.14-alpine3.16 
    command: ["/etc/sentinel.conf"]
    entrypoint: ["redis-sentinel"]
    networks:
      redis_net:
        ipv4_address: 172.16.200.14
    volumes:
      - ./config/sentinel-c.conf:/etc/sentinel.conf
    links:
      - redis-m
      - redis-s
      - redis-ss
networks:
  redis_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24
