---
- hosts: "{{ dkserver }}"
  remote_user: root
  gather_facts: no
  vars:
   fedir: /data/webapps/cmsfrontend/webroot/
   software: [rsync]

  tasks:  
  - name: create dir 
    file: path={{ fedir }} state=directory

  #- name: rsync install
  #  yum: name={{ software }}

  #- name: configure ssh connection by sshkey
  #  block:
  #   - copy: src="../config/myansible.pub" dest="/tmp/authorized_keys"
  #   - file: path="~/.ssh" state=directory
  #   - shell: cat /tmp/authorized_keys >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && rm -rf /tmp/authorized_keys

  - name: sync fe file
    synchronize: src=./fe/test/ dest={{fedir}}
