---
- hosts: C
  remote_user: root
  gather_facts: no
  tasks:
  - shell: echo {{testvar|quote}} >/tmp/k2
    vars:
     testvar: "abce\nworld\n"
  - debug:
     msg: "{{(name=='john11111111111')|ternary('Mr','Ms')}}"
    vars:
     name: "john"
  - debug:
     msg: "{{testvar|basename}}"
    vars:
     testvar: "/root/etc/tmp/1.txt"
  - debug:
     msg: "{{testvar|win_basename}}"
    vars:
     testvar: 'D:\root\atc\tmp\abc.txt'
  - debug:
     msg: "{{testvar|dirname}}"
    vars:
     testvar: "/root/etc/tmp/1.txt"
  - debug:
     msg: "{{testvar|win_dirname}}"
    vars:
     testvar: 'D:\root\atc\tmp\abc.txt'
  - debug:
     msg: "{{ testvar|win_splitdrive|last }}"
    vars:
     testvar: 'D:\root\atc\tmp\abc.txt'
  - debug:
     msg: "{{testvar|realpath}}"
    vars:
     testvar: '/tmp/11111.txt'
  - debug:
     msg: "{{testvar|splitext|first}}"
    vars:
     testvar: '/tmp/11111.txt'
  - debug:
     msg: "{{testvar|to_uuid}}"
    vars:
     testvar: '/tmp/11111.txt'
  - debug:
     msg: "{{ teststr | bool }}"
    vars:
     teststr: "1"
  - debug:
#     msg: "{{users|map(attribute='name')|list}}"
     msg: "{{users|map(attribute='hobby')|join(';')}}"
    vars:
      users:
      - name: tom
        age: 18
        hobby:
        - Skateboard
        - VideoGame
      - name: jerry
        age: 20
        hobby:
        - Music
  - debug:
      msg: '{{(("2015-08-01 18:27:10"|to_datetime)-("2018-12-27 21:00:00"|to_datetime))|abs}}'
  - debug:
      msg: '{{((("2015-08-01 18:27:10"|to_datetime)-("2018-12-27 21:00:00"|to_datetime))|abs).total_seconds()}}'
  - debug:
      msg: '{{((("2015-08-01 18:27:10"|to_datetime)-("2018-12-27 21:00:00"|to_datetime))|abs).seconds}}'
  - debug:
      msg: '{{((("2015-08-01 18:27:10"|to_datetime)-("2018-12-27 21:00:00"|to_datetime))|abs).days}}'
  - debug:
      msg: "{{ 'hello' | b64encode }}"
  - debug:
      msg: "{{ 'aGVsbG8=' | b64decode }}"
  - debug:
      msg: "{{'123456' | hash('md5')}}"
  - debug:
      msg: "{{'abcdef' | hash('sha1')}}"
  - debug:
      msg: "{{'123456' | hash('checksum')}}"
  - debug:
      msg: "{{'123456' | hash('blowfish')}}"
  - debug:
      msg: "{{'123456' | password_hash('sha256')}}"
  - debug:
      msg: "{{'123456' | password_hash('sha256','mysalt')}}"
  - debug:
      msg: "{{'123456' | password_hash('sha512','mysalt')}}"
  - debug:
      msg: "{{'123456' | password_hash('sha512')}}"
  - debug:
      msg: "{{ '123123' | password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
  - debug:
      msg: "{{65534|random(seed=inventory_hostname)|string }}"
  - debug:
      msg: "{{65534|random(seed=inventory_hostname) }}"
