---
- hosts: C
  remote_user: root
  gather_facts: no
  tasks:
  - debug:
     msg: "{{item}}"
    with_items: 
    - [1,2,3]
    - [4,5,6]
    - [/data/a,/data/b]
  - debug:
     msg: "{{inventory_hostname}}"
