---
- hosts: C
  remote_user: root
  tasks:
  - debug:
      msg: "System release is centos7"
    when: ansible_distribution == "CentOS" and 
          (ansible_distribution_major_version == "7" or ansible_distribution_major_version == "6")
